added both html and css contents
Tekcoder/Apple-clone pull request #1
Opened 2019-09-24 22:21 UTC by Tekcoder

Completed the structure of the website

2019-09-24 23:08 UTC, stratospherique reviewed
### Pull request under review by Ahmed Mahfoudh TSE

2019-09-24 23:34 UTC, stratospherique requested changes
### Great work :clap: However, some requirements needs to be implemented in order to get approval for your project. check below :arrow_down: 

#### Page structure

#### Navbar

![image](https://user-images.githubusercontent.com/26124023/65557399-17f48780-df2b-11e9-813c-d15db7265eeb.png)

- You have a undesirable visible border for the search input (it's overflowing). :pray: fix.

#### Bottom

* [ ] It contains four elements which are links (to another articles or `#`)
- Wrap each image inside a link and make it clickable.

#### General requirements:

- You linter is not properly configured. Check Microverse [guide](https://github.com/microverseinc/linters-config/tree/master/css) and follow the listed instructions.

- Add more info to your readme file (e.g. project descirption, technologies used, assignment link, your profile link, etc...)

### That's it :relieved: . When finished, kindly resubmit another code review  form :pray:

2019-09-25 23:53 UTC, Redvanisation requested changes
### Hello @Tekcoder 

**Good work on this project, but we need to fix the issues mentioned below before moving on ⬇️** 

1. You have a **white background on the search** icon in the navbar, please fix that.

2. Fix all the **linter's errors**.

### _After making the required changes please submit a new code review request_

### Good luck! 🍀

2019-09-26 22:23 UTC, Forison reviewed
# pull request under review by ADDO

2019-09-26 22:46 UTC, Forison requested changes
Hi @Tekcoder 
Thanks for addressing some of the issues addressed by the TSE, however, some issues still prevail.
here are a few changes we can make before merging.
- This does not look good
![Screenshot from 2019-09-26 18-27-28](https://user-images.githubusercontent.com/29695661/65729424-3a51e680-e08c-11e9-9eca-34935614db64.png)
> fix this by wrapping by placing the navbar inside the section with class ```.hero```
> give the navbar a position attribute "relative" instead of absolute.

- the bottom does not look good
![Screenshot from 2019-09-26 18-27-38](https://user-images.githubusercontent.com/29695661/65729625-f3182580-e08c-11e9-9918-764dade17139.png)
check the dimensions, to be precise their widths
>all four elements combined must have a width of 100%, hence each must have a width of 25%. with this they would align as they should

-  You should fix the warning given to you by the[ validator ](https://validator.w3.org)when uploading the index file.🙂
> you can use ```div```

#### Kindly fix these issues and submit for review 🙂
#### That is it @Tekcoder 🙂🙂
Happy Coding

2019-09-27 20:40 UTC, samgaco approved these changes
Hi :high_brightness: The project is approved :white_check_mark: you may merge to the master branch and submit the project completion form. Congratulations on finishing your first solo project :+1: 

-----------------

* ###### STATUS OF THE PROJECT: APPROVED :heavy_check_mark:

2019-09-27 20:40 UTC, samgaco commented on style.css
> +  position: relative;
:+1: 

[OPTIONAL]

What about improving this part a bit more so the navbar is more centered, and have some space left at the top? To simulate the original page in a better manner

2019-09-27 23:02 UTC, merged